# Welcome to Jekyll!

# Site settings
title: Machine Learning 
name: Ajit Jasrotia
email: ajitjasrotia012@gmail.com
location: Chandigarh, India 
company: Constalytics
company_url: https://constalytics.com
github_url: https://github.com/ajitjasrotia 
github_username: AjitJasrotia 
description: Machine Learning is site for new candidate that are trying to learn Machine Learning from basics.
favicon: favicon.png 
repository: ajitjasrotia/ajitjasrotia.github.io 

# For production, use your github page url. 
url: https://ajitjasrotia.github.io/

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'
Logistic Regression is a classification algorithm. It is used to predict a binary outcome (1 / 0, Yes / No, True / False) given a set of independent variables. To represent binary / categorical outcome, we use dummy variables. You can also think of logistic regression as a special case of linear regression when the outcome variable is categorical, where we are using log of odds as dependent variable. In simple words, it predicts the probability of occurrence of an event by fitting data to a logit function.
# Navigation. If you do not like these modules, just remove them :
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 
